In [1]:
import pandas as pd

In [2]:
dataset=pd.read_csv("Social_Network_Ads.csv")

In [3]:
dataset

      User ID  Gender  Age  EstimatedSalary  Purchased
0    15624510    Male   19            19000          0
1    15810944    Male   35            20000          0
2    15668575  Female   26            43000          0
3    15603246  Female   27            57000          0
4    15804002    Male   19            76000          0
..        ...     ...  ...              ...        ...
395  15691863  Female   46            41000          1
396  15706071    Male   51            23000          1
397  15654296  Female   50            20000          1
398  15755018    Male   36            33000          0
399  15594041  Female   49            36000          1

[400 rows x 5 columns]

In [4]:
dataset=dataset.drop("User ID",axis=1)

In [5]:
dataset

     Gender  Age  EstimatedSalary  Purchased
0      Male   19            19000          0
1      Male   35            20000          0
2    Female   26            43000          0
3    Female   27            57000          0
4      Male   19            76000          0
..      ...  ...              ...        ...
395  Female   46            41000          1
396    Male   51            23000          1
397  Female   50            20000          1
398    Male   36            33000          0
399  Female   49            36000          1

[400 rows x 4 columns]

In [6]:
dataset=pd.get_dummies(dataset,drop_first=True)

In [7]:
dataset.columns

Index(['Age', 'EstimatedSalary', 'Purchased', 'Gender_Male'], dtype='object')

In [8]:
independent=dataset[['Age', 'EstimatedSalary','Gender_Male']]
dependent=dataset[['Purchased']]

In [9]:
# training set split 
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(independent,dependent,test_size=0.3,random_state=0)

In [12]:
# model creation using GridSearchCV 
from sklearn.model_selection import GridSearchCV
from sklearn.tree import DecisionTreeClassifier
param_grid={'criterion':['gini','entropy','log_loss'],
              'max_features':['sqrt','log2'],
               'splitter':['best','random']}
grid=GridSearchCV(DecisionTreeClassifier(),param_grid,refit=True,verbose=3,n_jobs=-1,scoring="f1_weighted")
grid.fit(x_train,y_train)

Fitting 5 folds for each of 12 candidates, totalling 60 fits

GridSearchCV(estimator=DecisionTreeClassifier(), n_jobs=-1,
             param_grid={'criterion': ['gini', 'entropy', 'log_loss'],
                         'max_features': ['sqrt', 'log2'],
                         'splitter': ['best', 'random']},
             scoring='f1_weighted', verbose=3)

In [16]:
print(grid.best_params_)
re=grid.cv_results_
y_predict=grid.predict(x_test)

from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test,y_predict)
print(cm)

from sklearn.metrics import classification_report
clf_report=classification_report(y_test,y_predict)
print(clf_report)

{'criterion': 'gini', 'max_features': 'log2', 'splitter': 'best'}
[[71  8]
 [ 4 37]]
              precision    recall  f1-score   support

           0       0.95      0.90      0.92        79
           1       0.82      0.90      0.86        41

    accuracy                           0.90       120
   macro avg       0.88      0.90      0.89       120
weighted avg       0.90      0.90      0.90       120

In [20]:
# f1 score 
from sklearn.metrics import f1_score
f1_macro=f1_score(y_test,y_predict,average="weighted")
print(f1_macro)

0.9010268800966474

In [21]:
#ROC_AUC
from sklearn.metrics import roc_auc_score
roc_auc=roc_auc_score(y_test,grid.predict_proba(x_test)[:,1])
print(roc_auc)

0.9005866008027168

In [26]:
# saving filename

import pickle
filename="DTclassifierGridSearchCV.sav"

pickle.dump(grid,open(filename,"wb"))
load_model=pickle.load(open("DTclassifierGridSearchCV.sav","rb"))

In [27]:
result=load_model.predict([[23,58222,0]])

C:\Anaconda3\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(

In [28]:
result

array([0])